<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsuarioSeeder extends Seeder
{
    public function run(): void
    {
        \Illuminate\Support\Facades\DB::table('mathews.usuarios')->insert([
            [
                'nome'            => 'Carlos Eduardo',
                'sexo'            => 'M',
                'data_nascimento' => '1982-04-12',
                'cpf'             => '101.101.101-01',
                'email'           => 'carlos@email.com',
                'senha'           => Hash::make('123456'),
                'tipo'            => 'comum',
                'telefone'        => '(11) 98888-1111',
                'cidade'          => 'São Paulo',
                'estado'          => 'SP',
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'nome'            => 'Ana Júlia',
                'sexo'            => 'F',
                'data_nascimento' => '1990-09-25',
                'cpf'             => '202.202.202-02',
                'email'           => 'ana@email.com',
                'senha'           => Hash::make('123456'),
                'tipo'            => 'comum',
                'telefone'        => '(21) 97777-2222',
                'cidade'          => 'Rio de Janeiro',
                'estado'          => 'RJ',
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'nome'            => 'Marcos Silva',
                'sexo'            => 'M',
                'data_nascimento' => '1975-11-03',
                'cpf'             => '303.303.303-03',
                'email'           => 'marcos@email.com',
                'senha'           => Hash::make('123456'),
                'tipo'            => 'comum',
                'telefone'        => '(31) 96666-3333',
                'cidade'          => 'Belo Horizonte',
                'estado'          => 'MG',
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'nome'            => 'Beatriz Costa',
                'sexo'            => 'F',
                'data_nascimento' => '2001-02-18',
                'cpf'             => '404.404.404-04',
                'email'           => 'beatriz@email.com',
                'senha'           => Hash::make('123456'),
                'tipo'            => 'comum',
                'telefone'        => '(41) 95555-4444',
                'cidade'          => 'Curitiba',
                'estado'          => 'PR',
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'nome'            => 'Fernando Souza',
                'sexo'            => 'M',
                'data_nascimento' => '1988-07-30',
                'cpf'             => '505.505.505-05',
                'email'           => 'fernando@email.com',
                'senha'           => Hash::make('123456'),
                'tipo'            => 'comum',
                'telefone'        => '(51) 94444-5555',
                'cidade'          => 'Porto Alegre',
                'estado'          => 'RS',
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'nome'            => 'Amanda Oliveira',
                'sexo'            => 'F',
                'data_nascimento' => '1995-12-14',
                'cpf'             => '606.606.606-06',
                'email'           => 'amanda@email.com',
                'senha'           => Hash::make('123456'),
                'tipo'            => 'comum',
                'telefone'        => '(61) 93333-6666',
                'cidade'          => 'Brasília',
                'estado'          => 'DF',
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'nome'            => 'Rafael Santos',
                'sexo'            => 'M',
                'data_nascimento' => '1992-05-08',
                'cpf'             => '707.707.707-07',
                'email'           => 'rafael@email.com',
                'senha'           => Hash::make('123456'),
                'tipo'            => 'comum',
                'telefone'        => '(71) 92222-7777',
                'cidade'          => 'Salvador',
                'estado'          => 'BA',
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'nome'            => 'Letícia Lima',
                'sexo'            => 'F',
                'data_nascimento' => '1985-10-21',
                'cpf'             => '808.808.808-08',
                'email'           => 'leticia@email.com',
                'senha'           => Hash::make('123456'),
                'tipo'            => 'comum',
                'telefone'        => '(81) 91111-8888',
                'cidade'          => 'Recife',
                'estado'          => 'PE',
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'nome'            => 'Thiago Pereira',
                'sexo'            => 'M',
                'data_nascimento' => '1979-01-15',
                'cpf'             => '909.909.909-09',
                'email'           => 'thiago@email.com',
                'senha'           => Hash::make('123456'),
                'tipo'            => 'comum',
                'telefone'        => '(85) 90000-9999',
                'cidade'          => 'Fortaleza',
                'estado'          => 'CE',
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'nome'            => 'Carolina Mendes',
                'sexo'            => 'F',
                'data_nascimento' => '1998-06-29',
                'cpf'             => '123.123.123-12',
                'email'           => 'carolina@email.com',
                'senha'           => Hash::make('123456'),
                'tipo'            => 'comum',
                'telefone'        => '(98) 98888-0000',
                'cidade'          => 'São Luís',
                'estado'          => 'MA',
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'nome'            => 'Diego Almeida',
                'sexo'            => 'M',
                'data_nascimento' => '1981-08-04',
                'cpf'             => '234.234.234-23',
                'email'           => 'diego@email.com',
                'senha'           => Hash::make('123456'),
                'tipo'            => 'comum',
                'telefone'        => '(62) 97777-1111',
                'cidade'          => 'Goiânia',
                'estado'          => 'GO',
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'nome'            => 'Juliana Rocha',
                'sexo'            => 'F',
                'data_nascimento' => '1993-03-11',
                'cpf'             => '345.345.345-34',
                'email'           => 'juliana@email.com',
                'senha'           => Hash::make('123456'),
                'tipo'            => 'comum',
                'telefone'        => '(67) 96666-2222',
                'cidade'          => 'Dourados',
                'estado'          => 'MS',
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'nome'            => 'Rodrigo Carvalho',
                'sexo'            => 'M',
                'data_nascimento' => '1986-12-02',
                'cpf'             => '456.456.456-45',
                'email'           => 'rodrigo@email.com',
                'senha'           => Hash::make('123456'),
                'tipo'            => 'comum',
                'telefone'        => '(65) 95555-3333',
                'cidade'          => 'Cuiabá',
                'estado'          => 'MT',
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'nome'            => 'Natália Ribeiro',
                'sexo'            => 'F',
                'data_nascimento' => '1991-04-19',
                'cpf'             => '567.567.567-56',
                'email'           => 'natalia@email.com',
                'senha'           => Hash::make('123456'),
                'tipo'            => 'comum',
                'telefone'        => '(92) 94444-4444',
                'cidade'          => 'Manaus',
                'estado'          => 'AM',
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'nome'            => 'Bruno Fernandes',
                'sexo'            => 'M',
                'data_nascimento' => '1989-09-07',
                'cpf'             => '678.678.678-67',
                'email'           => 'bruno@email.com',
                'senha'           => Hash::make('123456'),
                'tipo'            => 'comum',
                'telefone'        => '(84) 93333-5555',
                'cidade'          => 'Natal',
                'estado'          => 'RN',
                'created_at'      => now(),
                'updated_at'      => now(),
            ]
        ]);
    }
}